//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_AspNetUsers_Claims", "AspNetUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.AspNetUsers), "AspNetUserClaims", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.AspNetUserClaims), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_AspNetUsers_Logins", "AspNetUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.AspNetUsers), "AspNetUserLogins", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.AspNetUserLogins), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_T_Users", "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Users), "AspNetUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.AspNetUsers), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_T_Users_AspNetUsers", "AspNetUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.AspNetUsers), "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_Users), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_Comment_Users", "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Users), "T_Comments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_Comments), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_Comment_Video", "T_Videos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Videos), "T_Comments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_Comments), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_Encode_Videos", "T_Videos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Videos), "T_Encode", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_Encode), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_VideosTags_Tags", "T_Tags", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Tags), "T_VideosTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_VideosTags), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_Videos_Users", "T_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Users), "T_Videos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_Videos), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "FK_VideosTags_Videos", "T_Videos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AdminBackend.DataAccess.T_Videos), "T_VideosTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.T_VideosTags), true)]
[assembly: EdmRelationshipAttribute("CatMyVideoModel", "AspNetUserRoles", "AspNetRoles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.AspNetRoles), "AspNetUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AdminBackend.DataAccess.AspNetUsers))]

#endregion

namespace AdminBackend.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CatMyVideoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CatMyVideoEntities object using the connection string found in the 'CatMyVideoEntities' section of the application configuration file.
        /// </summary>
        public CatMyVideoEntities() : base("name=CatMyVideoEntities", "CatMyVideoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CatMyVideoEntities object.
        /// </summary>
        public CatMyVideoEntities(string connectionString) : base(connectionString, "CatMyVideoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CatMyVideoEntities object.
        /// </summary>
        public CatMyVideoEntities(EntityConnection connection) : base(connection, "CatMyVideoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AspNetRoles> AspNetRoles
        {
            get
            {
                if ((_AspNetRoles == null))
                {
                    _AspNetRoles = base.CreateObjectSet<AspNetRoles>("AspNetRoles");
                }
                return _AspNetRoles;
            }
        }
        private ObjectSet<AspNetRoles> _AspNetRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AspNetUserClaims> AspNetUserClaims
        {
            get
            {
                if ((_AspNetUserClaims == null))
                {
                    _AspNetUserClaims = base.CreateObjectSet<AspNetUserClaims>("AspNetUserClaims");
                }
                return _AspNetUserClaims;
            }
        }
        private ObjectSet<AspNetUserClaims> _AspNetUserClaims;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AspNetUserLogins> AspNetUserLogins
        {
            get
            {
                if ((_AspNetUserLogins == null))
                {
                    _AspNetUserLogins = base.CreateObjectSet<AspNetUserLogins>("AspNetUserLogins");
                }
                return _AspNetUserLogins;
            }
        }
        private ObjectSet<AspNetUserLogins> _AspNetUserLogins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AspNetUsers> AspNetUsers
        {
            get
            {
                if ((_AspNetUsers == null))
                {
                    _AspNetUsers = base.CreateObjectSet<AspNetUsers>("AspNetUsers");
                }
                return _AspNetUsers;
            }
        }
        private ObjectSet<AspNetUsers> _AspNetUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Comments> T_Comments
        {
            get
            {
                if ((_T_Comments == null))
                {
                    _T_Comments = base.CreateObjectSet<T_Comments>("T_Comments");
                }
                return _T_Comments;
            }
        }
        private ObjectSet<T_Comments> _T_Comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Encode> T_Encode
        {
            get
            {
                if ((_T_Encode == null))
                {
                    _T_Encode = base.CreateObjectSet<T_Encode>("T_Encode");
                }
                return _T_Encode;
            }
        }
        private ObjectSet<T_Encode> _T_Encode;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Tags> T_Tags
        {
            get
            {
                if ((_T_Tags == null))
                {
                    _T_Tags = base.CreateObjectSet<T_Tags>("T_Tags");
                }
                return _T_Tags;
            }
        }
        private ObjectSet<T_Tags> _T_Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Users> T_Users
        {
            get
            {
                if ((_T_Users == null))
                {
                    _T_Users = base.CreateObjectSet<T_Users>("T_Users");
                }
                return _T_Users;
            }
        }
        private ObjectSet<T_Users> _T_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Videos> T_Videos
        {
            get
            {
                if ((_T_Videos == null))
                {
                    _T_Videos = base.CreateObjectSet<T_Videos>("T_Videos");
                }
                return _T_Videos;
            }
        }
        private ObjectSet<T_Videos> _T_Videos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_VideosTags> T_VideosTags
        {
            get
            {
                if ((_T_VideosTags == null))
                {
                    _T_VideosTags = base.CreateObjectSet<T_VideosTags>("T_VideosTags");
                }
                return _T_VideosTags;
            }
        }
        private ObjectSet<T_VideosTags> _T_VideosTags;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AspNetRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAspNetRoles(AspNetRoles aspNetRoles)
        {
            base.AddObject("AspNetRoles", aspNetRoles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AspNetUserClaims EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAspNetUserClaims(AspNetUserClaims aspNetUserClaims)
        {
            base.AddObject("AspNetUserClaims", aspNetUserClaims);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AspNetUserLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAspNetUserLogins(AspNetUserLogins aspNetUserLogins)
        {
            base.AddObject("AspNetUserLogins", aspNetUserLogins);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AspNetUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAspNetUsers(AspNetUsers aspNetUsers)
        {
            base.AddObject("AspNetUsers", aspNetUsers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Comments(T_Comments t_Comments)
        {
            base.AddObject("T_Comments", t_Comments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Encode EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Encode(T_Encode t_Encode)
        {
            base.AddObject("T_Encode", t_Encode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Tags(T_Tags t_Tags)
        {
            base.AddObject("T_Tags", t_Tags);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Users(T_Users t_Users)
        {
            base.AddObject("T_Users", t_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Videos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Videos(T_Videos t_Videos)
        {
            base.AddObject("T_Videos", t_Videos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_VideosTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_VideosTags(T_VideosTags t_VideosTags)
        {
            base.AddObject("T_VideosTags", t_VideosTags);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="AspNetRoles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AspNetRoles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AspNetRoles object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static AspNetRoles CreateAspNetRoles(global::System.String id, global::System.String name)
        {
            AspNetRoles aspNetRoles = new AspNetRoles();
            aspNetRoles.Id = id;
            aspNetRoles.Name = name;
            return aspNetRoles;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "AspNetUserRoles", "AspNetUsers")]
        public EntityCollection<AspNetUsers> AspNetUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AspNetUsers>("CatMyVideoModel.AspNetUserRoles", "AspNetUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AspNetUsers>("CatMyVideoModel.AspNetUserRoles", "AspNetUsers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="AspNetUserClaims")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AspNetUserClaims : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AspNetUserClaims object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static AspNetUserClaims CreateAspNetUserClaims(global::System.Int32 id, global::System.String userId)
        {
            AspNetUserClaims aspNetUserClaims = new AspNetUserClaims();
            aspNetUserClaims.Id = id;
            aspNetUserClaims.UserId = userId;
            return aspNetUserClaims;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClaimType
        {
            get
            {
                return _ClaimType;
            }
            set
            {
                OnClaimTypeChanging(value);
                ReportPropertyChanging("ClaimType");
                _ClaimType = StructuralObject.SetValidValue(value, true, "ClaimType");
                ReportPropertyChanged("ClaimType");
                OnClaimTypeChanged();
            }
        }
        private global::System.String _ClaimType;
        partial void OnClaimTypeChanging(global::System.String value);
        partial void OnClaimTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClaimValue
        {
            get
            {
                return _ClaimValue;
            }
            set
            {
                OnClaimValueChanging(value);
                ReportPropertyChanging("ClaimValue");
                _ClaimValue = StructuralObject.SetValidValue(value, true, "ClaimValue");
                ReportPropertyChanged("ClaimValue");
                OnClaimValueChanged();
            }
        }
        private global::System.String _ClaimValue;
        partial void OnClaimValueChanging(global::System.String value);
        partial void OnClaimValueChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_AspNetUsers_Claims", "AspNetUsers")]
        public AspNetUsers AspNetUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Claims", "AspNetUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Claims", "AspNetUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AspNetUsers> AspNetUsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Claims", "AspNetUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Claims", "AspNetUsers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="AspNetUserLogins")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AspNetUserLogins : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AspNetUserLogins object.
        /// </summary>
        /// <param name="loginProvider">Initial value of the LoginProvider property.</param>
        /// <param name="providerKey">Initial value of the ProviderKey property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static AspNetUserLogins CreateAspNetUserLogins(global::System.String loginProvider, global::System.String providerKey, global::System.String userId)
        {
            AspNetUserLogins aspNetUserLogins = new AspNetUserLogins();
            aspNetUserLogins.LoginProvider = loginProvider;
            aspNetUserLogins.ProviderKey = providerKey;
            aspNetUserLogins.UserId = userId;
            return aspNetUserLogins;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginProvider
        {
            get
            {
                return _LoginProvider;
            }
            set
            {
                if (_LoginProvider != value)
                {
                    OnLoginProviderChanging(value);
                    ReportPropertyChanging("LoginProvider");
                    _LoginProvider = StructuralObject.SetValidValue(value, false, "LoginProvider");
                    ReportPropertyChanged("LoginProvider");
                    OnLoginProviderChanged();
                }
            }
        }
        private global::System.String _LoginProvider;
        partial void OnLoginProviderChanging(global::System.String value);
        partial void OnLoginProviderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProviderKey
        {
            get
            {
                return _ProviderKey;
            }
            set
            {
                if (_ProviderKey != value)
                {
                    OnProviderKeyChanging(value);
                    ReportPropertyChanging("ProviderKey");
                    _ProviderKey = StructuralObject.SetValidValue(value, false, "ProviderKey");
                    ReportPropertyChanged("ProviderKey");
                    OnProviderKeyChanged();
                }
            }
        }
        private global::System.String _ProviderKey;
        partial void OnProviderKeyChanging(global::System.String value);
        partial void OnProviderKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, false, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_AspNetUsers_Logins", "AspNetUsers")]
        public AspNetUsers AspNetUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Logins", "AspNetUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Logins", "AspNetUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AspNetUsers> AspNetUsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Logins", "AspNetUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AspNetUsers>("CatMyVideoModel.FK_AspNetUsers_Logins", "AspNetUsers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="AspNetUsers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AspNetUsers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AspNetUsers object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="emailConfirmed">Initial value of the EmailConfirmed property.</param>
        /// <param name="phoneNumberConfirmed">Initial value of the PhoneNumberConfirmed property.</param>
        /// <param name="twoFactorEnabled">Initial value of the TwoFactorEnabled property.</param>
        /// <param name="lockoutEnabled">Initial value of the LockoutEnabled property.</param>
        /// <param name="accessFailedCount">Initial value of the AccessFailedCount property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="t_UserId">Initial value of the T_UserId property.</param>
        public static AspNetUsers CreateAspNetUsers(global::System.String id, global::System.Boolean emailConfirmed, global::System.Boolean phoneNumberConfirmed, global::System.Boolean twoFactorEnabled, global::System.Boolean lockoutEnabled, global::System.Int32 accessFailedCount, global::System.String userName, global::System.Int32 t_UserId)
        {
            AspNetUsers aspNetUsers = new AspNetUsers();
            aspNetUsers.Id = id;
            aspNetUsers.EmailConfirmed = emailConfirmed;
            aspNetUsers.PhoneNumberConfirmed = phoneNumberConfirmed;
            aspNetUsers.TwoFactorEnabled = twoFactorEnabled;
            aspNetUsers.LockoutEnabled = lockoutEnabled;
            aspNetUsers.AccessFailedCount = accessFailedCount;
            aspNetUsers.UserName = userName;
            aspNetUsers.T_UserId = t_UserId;
            return aspNetUsers;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EmailConfirmed
        {
            get
            {
                return _EmailConfirmed;
            }
            set
            {
                OnEmailConfirmedChanging(value);
                ReportPropertyChanging("EmailConfirmed");
                _EmailConfirmed = StructuralObject.SetValidValue(value, "EmailConfirmed");
                ReportPropertyChanged("EmailConfirmed");
                OnEmailConfirmedChanged();
            }
        }
        private global::System.Boolean _EmailConfirmed;
        partial void OnEmailConfirmedChanging(global::System.Boolean value);
        partial void OnEmailConfirmedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordHash
        {
            get
            {
                return _PasswordHash;
            }
            set
            {
                OnPasswordHashChanging(value);
                ReportPropertyChanging("PasswordHash");
                _PasswordHash = StructuralObject.SetValidValue(value, true, "PasswordHash");
                ReportPropertyChanged("PasswordHash");
                OnPasswordHashChanged();
            }
        }
        private global::System.String _PasswordHash;
        partial void OnPasswordHashChanging(global::System.String value);
        partial void OnPasswordHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecurityStamp
        {
            get
            {
                return _SecurityStamp;
            }
            set
            {
                OnSecurityStampChanging(value);
                ReportPropertyChanging("SecurityStamp");
                _SecurityStamp = StructuralObject.SetValidValue(value, true, "SecurityStamp");
                ReportPropertyChanged("SecurityStamp");
                OnSecurityStampChanged();
            }
        }
        private global::System.String _SecurityStamp;
        partial void OnSecurityStampChanging(global::System.String value);
        partial void OnSecurityStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PhoneNumberConfirmed
        {
            get
            {
                return _PhoneNumberConfirmed;
            }
            set
            {
                OnPhoneNumberConfirmedChanging(value);
                ReportPropertyChanging("PhoneNumberConfirmed");
                _PhoneNumberConfirmed = StructuralObject.SetValidValue(value, "PhoneNumberConfirmed");
                ReportPropertyChanged("PhoneNumberConfirmed");
                OnPhoneNumberConfirmedChanged();
            }
        }
        private global::System.Boolean _PhoneNumberConfirmed;
        partial void OnPhoneNumberConfirmedChanging(global::System.Boolean value);
        partial void OnPhoneNumberConfirmedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TwoFactorEnabled
        {
            get
            {
                return _TwoFactorEnabled;
            }
            set
            {
                OnTwoFactorEnabledChanging(value);
                ReportPropertyChanging("TwoFactorEnabled");
                _TwoFactorEnabled = StructuralObject.SetValidValue(value, "TwoFactorEnabled");
                ReportPropertyChanged("TwoFactorEnabled");
                OnTwoFactorEnabledChanged();
            }
        }
        private global::System.Boolean _TwoFactorEnabled;
        partial void OnTwoFactorEnabledChanging(global::System.Boolean value);
        partial void OnTwoFactorEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LockoutEndDateUtc
        {
            get
            {
                return _LockoutEndDateUtc;
            }
            set
            {
                OnLockoutEndDateUtcChanging(value);
                ReportPropertyChanging("LockoutEndDateUtc");
                _LockoutEndDateUtc = StructuralObject.SetValidValue(value, "LockoutEndDateUtc");
                ReportPropertyChanged("LockoutEndDateUtc");
                OnLockoutEndDateUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _LockoutEndDateUtc;
        partial void OnLockoutEndDateUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnLockoutEndDateUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LockoutEnabled
        {
            get
            {
                return _LockoutEnabled;
            }
            set
            {
                OnLockoutEnabledChanging(value);
                ReportPropertyChanging("LockoutEnabled");
                _LockoutEnabled = StructuralObject.SetValidValue(value, "LockoutEnabled");
                ReportPropertyChanged("LockoutEnabled");
                OnLockoutEnabledChanged();
            }
        }
        private global::System.Boolean _LockoutEnabled;
        partial void OnLockoutEnabledChanging(global::System.Boolean value);
        partial void OnLockoutEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccessFailedCount
        {
            get
            {
                return _AccessFailedCount;
            }
            set
            {
                OnAccessFailedCountChanging(value);
                ReportPropertyChanging("AccessFailedCount");
                _AccessFailedCount = StructuralObject.SetValidValue(value, "AccessFailedCount");
                ReportPropertyChanged("AccessFailedCount");
                OnAccessFailedCountChanged();
            }
        }
        private global::System.Int32 _AccessFailedCount;
        partial void OnAccessFailedCountChanging(global::System.Int32 value);
        partial void OnAccessFailedCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 T_UserId
        {
            get
            {
                return _T_UserId;
            }
            set
            {
                OnT_UserIdChanging(value);
                ReportPropertyChanging("T_UserId");
                _T_UserId = StructuralObject.SetValidValue(value, "T_UserId");
                ReportPropertyChanged("T_UserId");
                OnT_UserIdChanged();
            }
        }
        private global::System.Int32 _T_UserId;
        partial void OnT_UserIdChanging(global::System.Int32 value);
        partial void OnT_UserIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_AspNetUsers_Claims", "AspNetUserClaims")]
        public EntityCollection<AspNetUserClaims> AspNetUserClaims
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AspNetUserClaims>("CatMyVideoModel.FK_AspNetUsers_Claims", "AspNetUserClaims");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AspNetUserClaims>("CatMyVideoModel.FK_AspNetUsers_Claims", "AspNetUserClaims", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_AspNetUsers_Logins", "AspNetUserLogins")]
        public EntityCollection<AspNetUserLogins> AspNetUserLogins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AspNetUserLogins>("CatMyVideoModel.FK_AspNetUsers_Logins", "AspNetUserLogins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AspNetUserLogins>("CatMyVideoModel.FK_AspNetUsers_Logins", "AspNetUserLogins", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_T_Users", "T_Users")]
        public T_Users T_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_T_Users", "T_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_T_Users", "T_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Users> T_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_T_Users", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Users>("CatMyVideoModel.FK_T_Users", "T_Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_T_Users_AspNetUsers", "T_Users")]
        public EntityCollection<T_Users> T_Users1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Users>("CatMyVideoModel.FK_T_Users_AspNetUsers", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Users>("CatMyVideoModel.FK_T_Users_AspNetUsers", "T_Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "AspNetUserRoles", "AspNetRoles")]
        public EntityCollection<AspNetRoles> AspNetRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AspNetRoles>("CatMyVideoModel.AspNetUserRoles", "AspNetRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AspNetRoles>("CatMyVideoModel.AspNetUserRoles", "AspNetRoles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="T_Comments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Comments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Comments object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="message">Initial value of the message property.</param>
        /// <param name="post_date">Initial value of the post_date property.</param>
        /// <param name="author">Initial value of the author property.</param>
        /// <param name="video">Initial value of the video property.</param>
        public static T_Comments CreateT_Comments(global::System.Int32 id, global::System.String message, global::System.DateTime post_date, global::System.Int32 author, global::System.Int32 video)
        {
            T_Comments t_Comments = new T_Comments();
            t_Comments.id = id;
            t_Comments.message = message;
            t_Comments.post_date = post_date;
            t_Comments.author = author;
            t_Comments.video = video;
            return t_Comments;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, false, "message");
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime post_date
        {
            get
            {
                return _post_date;
            }
            set
            {
                Onpost_dateChanging(value);
                ReportPropertyChanging("post_date");
                _post_date = StructuralObject.SetValidValue(value, "post_date");
                ReportPropertyChanged("post_date");
                Onpost_dateChanged();
            }
        }
        private global::System.DateTime _post_date;
        partial void Onpost_dateChanging(global::System.DateTime value);
        partial void Onpost_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, "author");
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.Int32 _author;
        partial void OnauthorChanging(global::System.Int32 value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 video
        {
            get
            {
                return _video;
            }
            set
            {
                OnvideoChanging(value);
                ReportPropertyChanging("video");
                _video = StructuralObject.SetValidValue(value, "video");
                ReportPropertyChanged("video");
                OnvideoChanged();
            }
        }
        private global::System.Int32 _video;
        partial void OnvideoChanging(global::System.Int32 value);
        partial void OnvideoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Comment_Users", "T_Users")]
        public T_Users T_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_Comment_Users", "T_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_Comment_Users", "T_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Users> T_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_Comment_Users", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Users>("CatMyVideoModel.FK_Comment_Users", "T_Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Comment_Video", "T_Videos")]
        public T_Videos T_Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_Comment_Video", "T_Videos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_Comment_Video", "T_Videos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Videos> T_VideosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_Comment_Video", "T_Videos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Videos>("CatMyVideoModel.FK_Comment_Video", "T_Videos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="T_Encode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Encode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Encode object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="video">Initial value of the video property.</param>
        /// <param name="is_base">Initial value of the is_base property.</param>
        /// <param name="is_encoded">Initial value of the is_encoded property.</param>
        /// <param name="input_format">Initial value of the input_format property.</param>
        /// <param name="quality">Initial value of the quality property.</param>
        public static T_Encode CreateT_Encode(global::System.Int32 id, global::System.Int32 video, global::System.Boolean is_base, global::System.Boolean is_encoded, global::System.String input_format, global::System.Int32 quality)
        {
            T_Encode t_Encode = new T_Encode();
            t_Encode.id = id;
            t_Encode.video = video;
            t_Encode.is_base = is_base;
            t_Encode.is_encoded = is_encoded;
            t_Encode.input_format = input_format;
            t_Encode.quality = quality;
            return t_Encode;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 video
        {
            get
            {
                return _video;
            }
            set
            {
                OnvideoChanging(value);
                ReportPropertyChanging("video");
                _video = StructuralObject.SetValidValue(value, "video");
                ReportPropertyChanged("video");
                OnvideoChanged();
            }
        }
        private global::System.Int32 _video;
        partial void OnvideoChanging(global::System.Int32 value);
        partial void OnvideoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_base
        {
            get
            {
                return _is_base;
            }
            set
            {
                Onis_baseChanging(value);
                ReportPropertyChanging("is_base");
                _is_base = StructuralObject.SetValidValue(value, "is_base");
                ReportPropertyChanged("is_base");
                Onis_baseChanged();
            }
        }
        private global::System.Boolean _is_base;
        partial void Onis_baseChanging(global::System.Boolean value);
        partial void Onis_baseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_encoded
        {
            get
            {
                return _is_encoded;
            }
            set
            {
                Onis_encodedChanging(value);
                ReportPropertyChanging("is_encoded");
                _is_encoded = StructuralObject.SetValidValue(value, "is_encoded");
                ReportPropertyChanged("is_encoded");
                Onis_encodedChanged();
            }
        }
        private global::System.Boolean _is_encoded;
        partial void Onis_encodedChanging(global::System.Boolean value);
        partial void Onis_encodedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String input_format
        {
            get
            {
                return _input_format;
            }
            set
            {
                Oninput_formatChanging(value);
                ReportPropertyChanging("input_format");
                _input_format = StructuralObject.SetValidValue(value, false, "input_format");
                ReportPropertyChanged("input_format");
                Oninput_formatChanged();
            }
        }
        private global::System.String _input_format;
        partial void Oninput_formatChanging(global::System.String value);
        partial void Oninput_formatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 quality
        {
            get
            {
                return _quality;
            }
            set
            {
                OnqualityChanging(value);
                ReportPropertyChanging("quality");
                _quality = StructuralObject.SetValidValue(value, "quality");
                ReportPropertyChanged("quality");
                OnqualityChanged();
            }
        }
        private global::System.Int32 _quality;
        partial void OnqualityChanging(global::System.Int32 value);
        partial void OnqualityChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Encode_Videos", "T_Videos")]
        public T_Videos T_Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_Encode_Videos", "T_Videos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_Encode_Videos", "T_Videos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Videos> T_VideosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_Encode_Videos", "T_Videos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Videos>("CatMyVideoModel.FK_Encode_Videos", "T_Videos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="T_Tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Tags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Tags object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        public static T_Tags CreateT_Tags(global::System.String name)
        {
            T_Tags t_Tags = new T_Tags();
            t_Tags.name = name;
            return t_Tags;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false, "name");
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_VideosTags_Tags", "T_VideosTags")]
        public EntityCollection<T_VideosTags> T_VideosTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_VideosTags>("CatMyVideoModel.FK_VideosTags_Tags", "T_VideosTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_VideosTags>("CatMyVideoModel.FK_VideosTags_Tags", "T_VideosTags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="T_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Users object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nickname">Initial value of the nickname property.</param>
        /// <param name="pass">Initial value of the pass property.</param>
        /// <param name="aspNetUsersId">Initial value of the AspNetUsersId property.</param>
        public static T_Users CreateT_Users(global::System.Int32 id, global::System.String nickname, global::System.String pass, global::System.String aspNetUsersId)
        {
            T_Users t_Users = new T_Users();
            t_Users.id = id;
            t_Users.nickname = nickname;
            t_Users.pass = pass;
            t_Users.AspNetUsersId = aspNetUsersId;
            return t_Users;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nickname
        {
            get
            {
                return _nickname;
            }
            set
            {
                OnnicknameChanging(value);
                ReportPropertyChanging("nickname");
                _nickname = StructuralObject.SetValidValue(value, false, "nickname");
                ReportPropertyChanged("nickname");
                OnnicknameChanged();
            }
        }
        private global::System.String _nickname;
        partial void OnnicknameChanging(global::System.String value);
        partial void OnnicknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, false, "pass");
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AspNetUsersId
        {
            get
            {
                return _AspNetUsersId;
            }
            set
            {
                OnAspNetUsersIdChanging(value);
                ReportPropertyChanging("AspNetUsersId");
                _AspNetUsersId = StructuralObject.SetValidValue(value, false, "AspNetUsersId");
                ReportPropertyChanged("AspNetUsersId");
                OnAspNetUsersIdChanged();
            }
        }
        private global::System.String _AspNetUsersId;
        partial void OnAspNetUsersIdChanging(global::System.String value);
        partial void OnAspNetUsersIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_T_Users", "AspNetUsers")]
        public EntityCollection<AspNetUsers> AspNetUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AspNetUsers>("CatMyVideoModel.FK_T_Users", "AspNetUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AspNetUsers>("CatMyVideoModel.FK_T_Users", "AspNetUsers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_T_Users_AspNetUsers", "AspNetUsers")]
        public AspNetUsers AspNetUsers1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_T_Users_AspNetUsers", "AspNetUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_T_Users_AspNetUsers", "AspNetUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AspNetUsers> AspNetUsers1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUsers>("CatMyVideoModel.FK_T_Users_AspNetUsers", "AspNetUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AspNetUsers>("CatMyVideoModel.FK_T_Users_AspNetUsers", "AspNetUsers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Comment_Users", "T_Comments")]
        public EntityCollection<T_Comments> T_Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Comments>("CatMyVideoModel.FK_Comment_Users", "T_Comments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Comments>("CatMyVideoModel.FK_Comment_Users", "T_Comments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Videos_Users", "T_Videos")]
        public EntityCollection<T_Videos> T_Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Videos>("CatMyVideoModel.FK_Videos_Users", "T_Videos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Videos>("CatMyVideoModel.FK_Videos_Users", "T_Videos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="T_Videos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Videos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Videos object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="upload_date">Initial value of the upload_date property.</param>
        /// <param name="view_count">Initial value of the view_count property.</param>
        /// <param name="uploader">Initial value of the uploader property.</param>
        public static T_Videos CreateT_Videos(global::System.Int32 id, global::System.String title, global::System.String description, global::System.DateTime upload_date, global::System.Int64 view_count, global::System.Int32 uploader)
        {
            T_Videos t_Videos = new T_Videos();
            t_Videos.id = id;
            t_Videos.title = title;
            t_Videos.description = description;
            t_Videos.upload_date = upload_date;
            t_Videos.view_count = view_count;
            t_Videos.uploader = uploader;
            return t_Videos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime upload_date
        {
            get
            {
                return _upload_date;
            }
            set
            {
                Onupload_dateChanging(value);
                ReportPropertyChanging("upload_date");
                _upload_date = StructuralObject.SetValidValue(value, "upload_date");
                ReportPropertyChanged("upload_date");
                Onupload_dateChanged();
            }
        }
        private global::System.DateTime _upload_date;
        partial void Onupload_dateChanging(global::System.DateTime value);
        partial void Onupload_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 view_count
        {
            get
            {
                return _view_count;
            }
            set
            {
                Onview_countChanging(value);
                ReportPropertyChanging("view_count");
                _view_count = StructuralObject.SetValidValue(value, "view_count");
                ReportPropertyChanged("view_count");
                Onview_countChanged();
            }
        }
        private global::System.Int64 _view_count;
        partial void Onview_countChanging(global::System.Int64 value);
        partial void Onview_countChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uploader
        {
            get
            {
                return _uploader;
            }
            set
            {
                OnuploaderChanging(value);
                ReportPropertyChanging("uploader");
                _uploader = StructuralObject.SetValidValue(value, "uploader");
                ReportPropertyChanged("uploader");
                OnuploaderChanged();
            }
        }
        private global::System.Int32 _uploader;
        partial void OnuploaderChanging(global::System.Int32 value);
        partial void OnuploaderChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Comment_Video", "T_Comments")]
        public EntityCollection<T_Comments> T_Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Comments>("CatMyVideoModel.FK_Comment_Video", "T_Comments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Comments>("CatMyVideoModel.FK_Comment_Video", "T_Comments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Encode_Videos", "T_Encode")]
        public EntityCollection<T_Encode> T_Encode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Encode>("CatMyVideoModel.FK_Encode_Videos", "T_Encode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Encode>("CatMyVideoModel.FK_Encode_Videos", "T_Encode", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_Videos_Users", "T_Users")]
        public T_Users T_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_Videos_Users", "T_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_Videos_Users", "T_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Users> T_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Users>("CatMyVideoModel.FK_Videos_Users", "T_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Users>("CatMyVideoModel.FK_Videos_Users", "T_Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_VideosTags_Videos", "T_VideosTags")]
        public EntityCollection<T_VideosTags> T_VideosTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_VideosTags>("CatMyVideoModel.FK_VideosTags_Videos", "T_VideosTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_VideosTags>("CatMyVideoModel.FK_VideosTags_Videos", "T_VideosTags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CatMyVideoModel", Name="T_VideosTags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_VideosTags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_VideosTags object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="video">Initial value of the video property.</param>
        /// <param name="tag">Initial value of the tag property.</param>
        public static T_VideosTags CreateT_VideosTags(global::System.Int32 id, global::System.Int32 video, global::System.String tag)
        {
            T_VideosTags t_VideosTags = new T_VideosTags();
            t_VideosTags.id = id;
            t_VideosTags.video = video;
            t_VideosTags.tag = tag;
            return t_VideosTags;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 video
        {
            get
            {
                return _video;
            }
            set
            {
                OnvideoChanging(value);
                ReportPropertyChanging("video");
                _video = StructuralObject.SetValidValue(value, "video");
                ReportPropertyChanged("video");
                OnvideoChanged();
            }
        }
        private global::System.Int32 _video;
        partial void OnvideoChanging(global::System.Int32 value);
        partial void OnvideoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tag
        {
            get
            {
                return _tag;
            }
            set
            {
                OntagChanging(value);
                ReportPropertyChanging("tag");
                _tag = StructuralObject.SetValidValue(value, false, "tag");
                ReportPropertyChanged("tag");
                OntagChanged();
            }
        }
        private global::System.String _tag;
        partial void OntagChanging(global::System.String value);
        partial void OntagChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_VideosTags_Tags", "T_Tags")]
        public T_Tags T_Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Tags>("CatMyVideoModel.FK_VideosTags_Tags", "T_Tags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Tags>("CatMyVideoModel.FK_VideosTags_Tags", "T_Tags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Tags> T_TagsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Tags>("CatMyVideoModel.FK_VideosTags_Tags", "T_Tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Tags>("CatMyVideoModel.FK_VideosTags_Tags", "T_Tags", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CatMyVideoModel", "FK_VideosTags_Videos", "T_Videos")]
        public T_Videos T_Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_VideosTags_Videos", "T_Videos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_VideosTags_Videos", "T_Videos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Videos> T_VideosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Videos>("CatMyVideoModel.FK_VideosTags_Videos", "T_Videos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Videos>("CatMyVideoModel.FK_VideosTags_Videos", "T_Videos", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
