//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminBackend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tags
    {
        public T_Tags()
        {
            this.T_Videos = new HashSet<T_Videos>();
        }
    
        public string name { get; set; }
    
        public virtual ICollection<T_Videos> T_Videos { get; set; }
    }
}
