//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Encode
    {
        public int id { get; set; }
        public int video { get; set; }
        public bool is_base { get; set; }
        public bool is_encoded { get; set; }
        public int quality { get; set; }
    
        public virtual T_Videos T_Videos { get; set; }
    }
}
