//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tags
    {
        public T_Tags()
        {
            this.T_Videos = new HashSet<T_Videos>();
        }
    
        public string name { get; set; }
    
        public virtual ICollection<T_Videos> T_Videos { get; set; }
    }
}
