//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class T_Users
    {
        public T_Users()
        {
            this.T_Comments = new HashSet<T_Comments>();
            this.T_Videos = new HashSet<T_Videos>();
        }
    
        public int id { get; set; }
        public string nickname { get; set; }
        public string mail { get; set; }
        public string pass { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<T_Comments> T_Comments { get; set; }
        public virtual ICollection<T_Videos> T_Videos { get; set; }
    }
}
