//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Videos
    {
        public T_Videos()
        {
            this.T_Comments = new HashSet<T_Comments>();
            this.T_Tags = new HashSet<T_Tags>();
            this.T_Encode = new HashSet<T_Encode>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime upload_date { get; set; }
        public long view_count { get; set; }
        public int uploader { get; set; }
    
        public virtual ICollection<T_Comments> T_Comments { get; set; }
        public virtual T_Users T_Users { get; set; }
        public virtual ICollection<T_Tags> T_Tags { get; set; }
        public virtual ICollection<T_Encode> T_Encode { get; set; }
    }
}
