//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatMyVideoEntities : DbContext
    {
        public CatMyVideoEntities()
            : base("name=CatMyVideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Comments> T_Comments { get; set; }
        public DbSet<T_Tags> T_Tags { get; set; }
        public DbSet<T_Users> T_Users { get; set; }
        public DbSet<T_Videos> T_Videos { get; set; }
    }
}
