//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comments
    {
        public System.Guid id { get; set; }
        public string message { get; set; }
        public System.DateTime post_date { get; set; }
        public System.Guid author { get; set; }
        public System.Guid video { get; set; }
    
        public virtual T_Users T_Users { get; set; }
        public virtual T_Videos T_Videos { get; set; }
    }
}
