//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatMyVideo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class T_Users
    {
        public T_Users()
        {
            this.T_Comments = new HashSet<T_Comments>();
            this.T_Videos = new HashSet<T_Videos>();
        }
    
        public int id { get; set; }
        public string nickname { get; set; }
        public string mail { get; set; }
        public string pass { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<T_Comments> T_Comments { get; set; }
        public virtual ICollection<T_Videos> T_Videos { get; set; }
    }
}
